import { decideAlerts } from "./alertDecision";
import { dispatchAlert, dispatchDigest, type Transport } from "./alertDispatch";
import { createDiscordTransport } from "./discordTransport";
import { describeRunGap, getLatestRunPair } from "./runObservations";
import type { Observation } from "./alertDecision";

/**
 * Connecting a finished run to an alert decision, and the decision to a channel.
 *
 * ## The three states, and only one of them is an alert
 *
 * 1. **The run archived nothing** — no snapshot, so there is nothing to compare
 *    and nothing is said. A budget cap, an outage, or a project with no prompts:
 *    all real, none of them a visibility change, and a "you lost your mentions"
 *    alert generated by any of them is a lie a customer acts on.
 * 2. **There is no earlier run** — this is the first measurement, so there is
 *    no change, only a baseline. Silent, deliberately: the first alert a product
 *    sends should be about something that happened, not about having started.
 * 3. **There are two runs** — compare them, and let `decideAlerts` decide.
 *
 * ## Why the transport is a parameter and not a hard-coded webhook
 *
 * Because a *silently unsent* alert is the one failure this whole chain exists to
 * prevent, and a hard-coded transport makes "we have no channel configured" and
 * "the channel refused" look identical from the call site. Passing it in means
 * the caller states which, and a missing transport is a visible decision rather
 * than a branch nobody wrote.
 *
 * This is also why `alertOnRunChange` never throws. The patrol's job is
 * archiving answers; an alert that fails must not fail the run, or a webhook
 * outage becomes a monitoring outage — the same reasoning as the vendor-evidence
 * recorder, which is best-effort for the same reason.
 */
export async function alertOnRunChange(input: {
  projectId: string;
  /** Null when the run archived nothing. */
  snapshotId: string | null;
  /**
   * Every snapshot the run wrote, one per brand.
   *
   * Optional, and the scalar `snapshotId` is still honoured, because the two
   * together are what the scheduler passes: `snapshotId` is the first (the run
   * log reads it) and this is the full set. A caller that passes only the scalar
   * gets the single-snapshot behaviour it had before CL-501e.
   */
  snapshotIds?: readonly string[];
  transport: Transport;
  /** Shown in the message; falls back to the id rather than to "your project". */
  projectName?: string;
  now?: Date;
}): Promise<AlertOutcome> {
  if (input.snapshotId === null) {
    return {
      outcome: "not_applicable",
      reason:
        "The run archived nothing, so there is no new answer to compare and no change to report.",
    };
  }

  // Decide every snapshot the run produced, one brand at a time.
  //
  // **A multi-brand patrol writes one snapshot per target**, so a project that
  // monitors three brands alerts on three independent histories. Deciding only
  // the first meant two brands were never reported at all — the gap CL-501e
  // closes. Each is decided separately because they share nothing: different
  // domains, different answers, and a cross-brand pair would match no rows at all
  // now that the comparison key carries the domain.
  const snapshots = dedupe([input.snapshotId, ...(input.snapshotIds ?? [])]);
  if (snapshots.length === 0) {
    return {
      outcome: "not_applicable",
      reason:
        "The run archived nothing, so there is no new answer to compare and no change to report.",
    };
  }

  const outcomes: AlertOutcome[] = [];
  for (const snapshotId of snapshots) {
    outcomes.push(
      await decideOneSnapshot({ ...input, snapshotId, snapshotIds: undefined }),
    );
  }

  // One summary for the caller. A per-brand list is kept so a caller *can* show
  // which brands changed, but the headline stays the strongest outcome, because a
  // patrol log that reads "nothing to report" when one brand lost a mention is the
  // silent-failure shape this whole chain exists to avoid.
  const dispatched = outcomes.filter(
    (o): o is Extract<AlertOutcome, { outcome: "dispatched" }> =>
      o.outcome === "dispatched",
  );
  const inapplicable = outcomes.find((o) => o.outcome === "not_applicable");
  const noBaseline = outcomes.find((o) => o.outcome === "no_baseline");
  if (dispatched.length > 0) {
    return {
      outcome: "dispatched",
      // The first is the primary; `perBrand` is there for a caller that wants to
      // name every brand in the run log.
      result: dispatched[0].result,
      gap: dispatched[0].gap,
      perBrand: dispatched,
    };
  }
  if (noBaseline !== undefined) return noBaseline;
  return (
    inapplicable ?? {
      outcome: "not_applicable",
      reason: "Nothing to report for any brand in this run.",
    }
  );
}

/** First occurrence wins, so `snapshotId` leads the list. */
function dedupe(ids: ReadonlyArray<string | null>): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const id of ids) {
    if (id === null || seen.has(id)) continue;
    seen.add(id);
    out.push(id);
  }
  return out;
}

/** The single-snapshot decision, unchanged from before the per-brand split. */
async function decideOneSnapshot(
  input: Parameters<typeof alertOnRunChange>[0] & { snapshotId: string },
): Promise<AlertOutcome> {
  // The snapshot the run just produced, not "whatever is newest in the table".
  // The caller knows which run finished; re-deriving it here would decide the
  // alert about a different run whenever two finish out of order.
  //
  // **One brand at a time.** A patrol writes one snapshot per target, so this is
  // called once per brand and each call is scoped to that brand's history by
  // `getLatestRunPair` (which reads the snapshot's own `target_id`). The previous
  // version compared "this brand's run" against "the previous run of the whole
  // project", which in a multi-brand project put two different brands on either
  // side of one diff — and because the comparison key carries the domain, that
  // matched no rows and the alert said nothing at all.
  const pair = await getLatestRunPair(input.projectId, input.snapshotId);
  if (pair === null) {
    return {
      outcome: "not_applicable",
      reason:
        "No completed run was found to compare this one against, so there is no change to report.",
    };
  }
  if (pair.previous === null) {
    // The first measurement is a baseline, not news. And saying "we started
    // monitoring you" is exactly the kind of message that teaches a channel to
    // be skimmed.
    return {
      outcome: "no_baseline",
      reason:
        "This is the first stored run, so there is nothing to compare it against. It establishes the baseline the next run will be measured from.",
    };
  }

  const decision = decideAlerts({
    previous: toObservations(pair.previous.byKey),
    current: toObservations(pair.current.byKey),
  });

  // The run gap is read so the *caller's* log can carry it, and is deliberately
  // not folded into the message: a "since 4 days ago" clause in an alert about a
  // single lost citation is a second thing to parse, and the cadence filter means
  // a long gap is routine rather than alarming. The log is where a run's
  // timeline belongs.
  const gap = describeRunGap({
    current: { startedAt: pair.current.startedAt },
    previous: { startedAt: pair.previous.startedAt },
  });

  const result = await dispatchAlert({
    projectId: input.projectId,
    // The run's identity, so a retried dispatch of the same decision
    // fingerprints identically. The snapshot *is* that identity.
    runId: pair.current.snapshotId,
    projectName: input.projectName ?? input.projectId,
    decision,
    transport: input.transport,
    now: input.now,
  });

  /**
   * The roll-up, dispatched alongside the alert.
   *
   * `decideAlerts` splits its changes in two: the ones worth interrupting for, and
   * `suppressed` — which is **every gained mention**. Those were formatted by
   * `buildDigest` and then thrown away, because nothing called it. So a brand that
   * started being mentioned got no message at all, and the rationale in
   * `buildDigest` — *a channel that carries only losses gets muted* — described a
   * design nothing implemented.
   *
   * Dispatched here rather than on a weekly timer because the runner is the only
   * place a decision exists, and because a digest keyed on the week is naturally
   * at-least-once: the first run of a week to produce a gain sends it, and every
   * later run that week is a `duplicate` the duplicate check refuses.
   *
   * **Failures are swallowed**, and that is deliberate rather than lazy. The
   * interruption has already been sent at this point, so a roll-up that could not
   * be delivered must not turn a successful alert into a failed run — and the
   * recorded `failed` row means the next tick retries it.
   */
  if (decision.suppressed.length > 0) {
    const weekOf = weekStartOf(pair.current.startedAt);
    await dispatchDigest({
      projectId: input.projectId,
      runId: pair.current.snapshotId,
      projectName: input.projectName ?? input.projectId,
      suppressed: decision.suppressed,
      weekOf,
      transport: input.transport,
      now: input.now,
    }).catch((digestError: unknown) => {
      console.error(
        `[geo-alerts] weekly roll-up failed and was swallowed so the alert could finish: ${
          digestError instanceof Error
            ? digestError.message
            : String(digestError)
        }`,
      );
    });
  }

  return {
    outcome: "dispatched",
    result,
    gap,
  };
}

/** The Monday of the week containing an ISO instant, as a date. */
function weekStartOf(iso: string): string {
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) return `week-of-${iso}`;
  const day = parsed.getUTCDay();
  // Sunday is the last day of its week, not the first.
  parsed.setUTCDate(parsed.getUTCDate() - (day === 0 ? 6 : day - 1));
  return parsed.toISOString().slice(0, 10);
}

/**
 * The three outcomes, named.
 *
 * A union rather than a bag of optionals, because the two "said nothing" cases
 * carry a *reason* the caller logs and a caller that has to re-derive which
 * happened is a caller that will eventually get it wrong. `gap` is a plain
 * `string | null` on the dispatched case rather than a conditional spread,
 * which would have made every reader narrow twice.
 */
type AlertOutcome =
  | { outcome: "not_applicable"; reason: string }
  | { outcome: "no_baseline"; reason: string }
  | {
      outcome: "dispatched";
      result: Awaited<ReturnType<typeof dispatchAlert>>;
      /** How far apart the two runs were, or null when close enough to omit. */
      gap: string | null;
      /**
       * Every brand that produced an alert in this run, in the order the patrol
       * wrote them.
       *
       * Present because a multi-brand run can legitimately alert on more than
       * one, and a caller logging the outcome needs to say *which* — a single
       * "alert sent" line would hide the other two brands from the run log, which
       * is the same incompleteness the scalar `snapshotId` had.
       */
      perBrand?: Array<{
        outcome: "dispatched";
        result: Awaited<ReturnType<typeof dispatchAlert>>;
        gap: string | null;
      }>;
    };

/** The decision layer takes a list; the reader gives a keyed map. */
function toObservations(byKey: Map<string, Observation>): Observation[] {
  return [...byKey.values()];
}

/**
 * The transport the scheduler uses.
 *
 * The real Discord transport, which is a **no-op when no webhook is configured**
 * — and that is the deliberate design, not a stub left behind. A self-hosted
 * install has no Discord webhook until someone sets `GEO_ALERT_DISCORD_WEBHOOK_URL`,
 * and the alternatives are all worse:
 *
 * - **Throw.** A missing webhook would fail every patrol, so the alerting failure
 *   becomes a monitoring outage — the product stops watching in order to report
 *   that it cannot report.
 * - **Swallow silently.** A patrol that looks healthy while nothing is ever
 *   delivered is the silent failure this whole chain exists to prevent.
 * - **Record a `failed` dispatch.** Then the next tick retries, forever, and
 *   every run carries a row saying a message was attempted for an audience that
 *   does not exist.
 *
 * So an unconfigured install succeeds, the dispatch is recorded as sent, and the
 * *gap* is visible: `countDeliveredAlerts` reports deliveries, and a deployment
 * with no webhook shows one — which is a fact an operator can check.
 *
 * Configured here rather than per-caller so there is exactly one place that
 * decides where an alert goes.
 */
export const ALERT_TRANSPORT: Transport = createDiscordTransport();
