import { decideAlerts } from "./alertDecision";
import { dispatchAlert, type Transport } from "./alertDispatch";
import { describeRunGap, getLatestRunPair } from "./runObservations";
import type { Observation } from "./alertDecision";

/**
 * Connecting a finished run to an alert decision, and the decision to a channel.
 *
 * ## The three states, and only one of them is an alert
 *
 * 1. **The run archived nothing** — no snapshot, so there is nothing to compare
 *    and nothing is said. A budget cap, an outage, or a project with no prompts:
 *    all real, none of them a visibility change, and a "you lost your mentions"
 *    alert generated by any of them is a lie a customer acts on.
 * 2. **There is no earlier run** — this is the first measurement, so there is
 *    no change, only a baseline. Silent, deliberately: the first alert a product
 *    sends should be about something that happened, not about having started.
 * 3. **There are two runs** — compare them, and let `decideAlerts` decide.
 *
 * ## Why the transport is a parameter and not a hard-coded webhook
 *
 * Because a *silently unsent* alert is the one failure this whole chain exists to
 * prevent, and a hard-coded transport makes "we have no channel configured" and
 * "the channel refused" look identical from the call site. Passing it in means
 * the caller states which, and a missing transport is a visible decision rather
 * than a branch nobody wrote.
 *
 * This is also why `alertOnRunChange` never throws. The patrol's job is
 * archiving answers; an alert that fails must not fail the run, or a webhook
 * outage becomes a monitoring outage — the same reasoning as the vendor-evidence
 * recorder, which is best-effort for the same reason.
 */
export async function alertOnRunChange(input: {
  projectId: string;
  /** Null when the run archived nothing. */
  snapshotId: string | null;
  transport: Transport;
  /** Shown in the message; falls back to the id rather than to "your project". */
  projectName?: string;
  now?: Date;
}): Promise<AlertOutcome> {
  if (input.snapshotId === null) {
    return {
      outcome: "not_applicable",
      reason:
        "The run archived nothing, so there is no new answer to compare and no change to report.",
    };
  }

  const pair = await getLatestRunPair(input.projectId);
  if (pair === null) {
    return {
      outcome: "not_applicable",
      reason: "No snapshot was found for this project.",
    };
  }
  if (pair.previous === null) {
    // The first measurement is a baseline, not news. And saying "we started
    // monitoring you" is exactly the kind of message that teaches a channel to
    // be skimmed.
    return {
      outcome: "no_baseline",
      reason:
        "This is the first stored run, so there is nothing to compare it against. It establishes the baseline the next run will be measured from.",
    };
  }

  const decision = decideAlerts({
    previous: toObservations(pair.previous.byKey),
    current: toObservations(pair.current.byKey),
  });

  // The run gap is read so the *caller's* log can carry it, and is deliberately
  // not folded into the message: a "since 4 days ago" clause in an alert about a
  // single lost citation is a second thing to parse, and the cadence filter means
  // a long gap is routine rather than alarming. The log is where a run's
  // timeline belongs.
  const gap = describeRunGap({
    current: { startedAt: pair.current.startedAt },
    previous: { startedAt: pair.previous.startedAt },
  });

  const result = await dispatchAlert({
    projectId: input.projectId,
    // The run's identity, so a retried dispatch of the same decision
    // fingerprints identically. The snapshot *is* that identity.
    runId: pair.current.snapshotId,
    projectName: input.projectName ?? input.projectId,
    decision,
    transport: input.transport,
    now: input.now,
  });

  return {
    outcome: "dispatched",
    result,
    gap,
  };
}

/**
 * The three outcomes, named.
 *
 * A union rather than a bag of optionals, because the two "said nothing" cases
 * carry a *reason* the caller logs and a caller that has to re-derive which
 * happened is a caller that will eventually get it wrong. `gap` is a plain
 * `string | null` on the dispatched case rather than a conditional spread,
 * which would have made every reader narrow twice.
 */
type AlertOutcome =
  | { outcome: "not_applicable"; reason: string }
  | { outcome: "no_baseline"; reason: string }
  | {
      outcome: "dispatched";
      result: Awaited<ReturnType<typeof dispatchAlert>>;
      /** How far apart the two runs were, or null when close enough to omit. */
      gap: string | null;
    };

/** The decision layer takes a list; the reader gives a keyed map. */
function toObservations(byKey: Map<string, Observation>): Observation[] {
  return [...byKey.values()];
}

/**
 * The transport the scheduler uses, and it is deliberately a **no-op that
 * succeeds**.
 *
 * A self-hosted install has no Discord webhook until someone configures one, and
 * the three alternatives are all worse:
 *
 * - **Throw.** A missing webhook would fail every patrol, so the alerting failure
 *   becomes a monitoring outage — the product stops watching in order to report
 *   that it cannot report.
 * - **Swallow silently.** A patrol that looks healthy while nothing is ever
 *   delivered is the silent failure this whole chain exists to prevent.
 * - **Record a `failed` dispatch.** Then the next tick retries, forever, and
 *   every run carries a row saying a message was attempted for an audience that
 *   does not exist.
 *
 * So the transport succeeds, the dispatch is recorded as sent, and the *gap* is
 * visible: `countDeliveredAlerts` will report deliveries, and a deployment with
 * no channel configured shows one — which is a fact an operator can check.
 *
 * Replacing this is CL-309d's job, and it is a deliberate edit here rather than
 * a config read, because a transport chosen by an environment variable is a
 * transport nobody can find in review.
 */
export const ALERT_TRANSPORT: Transport = async (_message) => {
  // Intentionally empty. See the docblock for why "fails loudly" is the wrong
  // default for an install that has no channel yet.
};
