import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * The vendor's category taxonomy: criterion ID to slash-path name.
 *
 * ## Why this table exists
 *
 * `categories_for_domain` returns each item's `categories` as **numeric criterion IDs** — an
 * array like `[10007]` — and the response contains **no labels anywhere**. A category profile
 * made of numbers is not a product, so the names have to come from somewhere, and the vendor
 * publishes them only as a CSV on their CDN (3,183 rows, `Criterion ID,Category`, category as a
 * slash-path hierarchy such as `/Apparel/Apparel Accessories/Bags & Packs`).
 *
 * ## Why a table rather than a bundle import or a fetch
 *
 * A bundle import would weight every worker cold start with a 267 KB asset; a runtime fetch would
 * make a third-party CDN a dependency of a read, adding a failure mode to a call that already has
 * a vendor behind it. A table is joinable, so a category's *name* and its *metrics* can be read
 * in one query, and it is **updatable without a deploy** — which matters because the file carries
 * a date in its name precisely because the vendor republishes it.
 *
 * ## The id is the vendor's, not ours
 *
 * `criterionId` is the vendor's criterion ID and the primary key, deliberately **not**
 * auto-increment: two ingests of the same taxonomy must land on the same rows, so the seed can be
 * re-run against a republished file without duplicating a single category. `path` is stored whole
 * rather than split into parent/child columns, because the hierarchy is the vendor's own
 * convention and a consumer can split on `/` for free.
 */
export const categoryTaxonomy = sqliteTable("category_taxonomy", {
  /** The vendor's criterion ID — `10007`. Never generated by us. */
  criterionId: integer("criterion_id").primaryKey(),
  /**
   * The full slash-path, e.g. `/Apparel/Apparel Accessories/Bags & Packs`.
   *
   * Whole rather than normalised into a tree: the vendor ships it as a path, its depth varies,
   * and nothing in this product needs a parent row to resolve a name.
   */
  path: text("path").notNull(),
});
