import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteDomainMetrics from "./domain-metrics.schema";
import * as sqliteProjectContext from "./project-context.schema";
import * as sqliteReports from "./reports.schema";
import * as sqliteReportTemplates from "./report-templates.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as sqliteGeo from "./geo.schema";
import * as sqliteVendorTasks from "./vendor-tasks.schema";
import * as sqliteMonitorRuns from "./monitor-runs.schema";
import * as sqlitePendingTasks from "./geo-pending-tasks.schema";
import * as sqliteAlertDispatches from "./alert-dispatches.schema";
import * as sqliteLabsCategories from "./labs-categories.schema";
import * as sqliteKeywordOpportunityInputs from "./keyword-opportunity-inputs.schema";
import * as pgApp from "./pg/app.schema";
import * as pgDomainMetrics from "./pg/domain-metrics.schema";
import * as pgProjectContext from "./pg/project-context.schema";
import * as pgReports from "./pg/reports.schema";
import * as pgReportTemplates from "./pg/report-templates.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as pgGeo from "./pg/geo.schema";
import * as pgVendorTasks from "./pg/vendor-tasks.schema";
import * as pgMonitorRuns from "./pg/monitor-runs.schema";
import * as pgPendingTasks from "./pg/geo-pending-tasks.schema";
import * as pgAlertDispatches from "./pg/alert-dispatches.schema";
import * as pgLabsCategories from "./pg/labs-categories.schema";
import * as pgKeywordOpportunityInputs from "./pg/keyword-opportunity-inputs.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteDomainMetrics &
  typeof sqliteProjectContext &
  typeof sqliteReports &
  typeof sqliteReportTemplates &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGa4 &
  typeof sqliteGsc &
  typeof sqliteTelemetry &
  typeof sqliteGeo &
  typeof sqliteVendorTasks &
  typeof sqliteMonitorRuns &
  typeof sqlitePendingTasks &
  typeof sqliteAlertDispatches &
  typeof sqliteLabsCategories &
  typeof sqliteKeywordOpportunityInputs;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgDomainMetrics,
        ...pgProjectContext,
        ...pgReports,
        ...pgReportTemplates,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGa4,
        ...pgGsc,
        ...pgTelemetry,
        ...pgGeo,
        ...pgVendorTasks,
        ...pgMonitorRuns,
        ...pgPendingTasks,
        ...pgAlertDispatches,
        ...pgLabsCategories,
        ...pgKeywordOpportunityInputs,
      }
    : {
        ...sqliteApp,
        ...sqliteDomainMetrics,
        ...sqliteProjectContext,
        ...sqliteReports,
        ...sqliteReportTemplates,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGa4,
        ...sqliteGsc,
        ...sqliteTelemetry,
        ...sqliteGeo,
        ...sqliteVendorTasks,
        ...sqliteMonitorRuns,
        ...sqlitePendingTasks,
        ...sqliteAlertDispatches,
        ...sqliteLabsCategories,
        ...sqliteKeywordOpportunityInputs,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  dashboardStepDismissals,
  backlinkSnapshots,
  domainMetrics,
  projectContextSections,
  projectCompetitors,
  projectKeyPages,
  projectResearchLog,
  reports,
  reportTemplates,
  audits,
  auditPages,
  auditIssues,
  auditLighthouseResults,
  auditReadiness,
  samSessions,
  user,
  session,
  account,
  apikey,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  ga4Connections,
  gscConnections,
  telemetryState,
  geoTargets,
  geoPromptSets,
  geoPrompts,
  geoSnapshots,
  geoAnswers,
  geoVendorTasks,
  geoAnswerCitations,
  geoAnswerRetrievals,
  geoFanoutQueries,
  geoSnapshotAnswers,
  geoTargetMetrics,
  geoCitationDomains,
  aiKeywordMetrics,
  aiMentionHistory,
  aiModeSnapshots,
  aiModeSnapshotCitations,
  monitorRuns,
  geoPendingTasks,
  geoAlertDispatches,
  categoryTaxonomy,
} = schema;
